graph LR
  Begin --> Create
  subgraph Loop
    Create --> Delay:Show
    Delay:Show --> Show
    Show --> Check:Dead
    Check:Dead --> Check:Drop
    subgraph Drop
      Check:Drop -- can drop --> Delay:Drop
      Delay:Drop --> Drop
      Drop --> Check:Drop
      Delay:Drop -- move block --> Check:Drop
    end
    Check:Drop -- cannot drop --> Delay:Lock
    Delay:Lock -- move block --> Check:Drop
    Delay:Lock --> Lock
    Lock --> Create
  end
  Create -- cannot place --> End
