graph LR
  Begin --> Create
  subgraph Loop
    Create --> Delay:Show
    Delay:Show --> Show
    Show --> Pending:Drop
    subgraph Drop
      Pending:Drop -- can drop --> Delay:Drop
      Delay:Drop --> Drop
      Drop --> Pending:Drop
      Delay:Drop -- move block --> Pending:Drop
    end
    Pending:Drop -- cannot drop --> Delay:Lock
    Delay:Lock -- move block --> Pending:Drop
    Delay:Lock --> Lock
    Lock --> Create
  end
  Create -- cannot place --> End
