graph LR
  Begin --> Create
  subgraph Loop
    Create --> Delay:Show
    Delay:Show --> Show
    Show --> Check:Dead
    Check:Dead --> Check:Drop
    subgraph Drop
      Check:Drop -- can drop --> Delay:Drop
      Delay:Drop --> Drop
      Drop --> Check:Drop
      Delay:Drop -- cannot drop --> Check:Drop
    end
    Check:Drop -- cannot drop --> Delay:Lock
    Delay:Lock -- can drop --> Check:Drop
    Delay:Drop -- hold --> Hold
    Delay:Lock -- hold --> Hold
    Hold --> Check:Dead
    Delay:Lock --> Lock
    Lock --> ClearLines
    ClearLines --> Create
  end
  Check:Dead --> End
