graph TB
  subgraph Input
    Keyboard -- key events --> KeyMapper
    Storage:Keyboard -- key settings --> KeyMapper
    KeyMapper -- mapped key events --> KeyStore
  end
  KeyStore -- key state --> Engine
  Ticker --> Engine
  Storage:Engine -- engine settings --> Engine
  Engine -- engine state --> Renderer
